spring.application.name=shortenurlapi

# Enable the browser-based GUI console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.trace=false
spring.h2.console.settings.web-allow-others=true

# Database connection settings
spring.datasource.url=jdbc:h2:mem:urlshortenerdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate/JPA auto-creation settings
spring.jpa.hibernate.ddl-auto=update

shortener.domain=https://chswb.com/
shortener.alias-pattern=^[a-zA-Z0-9]+$
